name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        django-version: ["3.2", "4.2", "5.1"]
        exclude:
          # Django 3.2 requires Python 3.6-3.10.
          - python-version: "3.11"
            django-version: "3.2"
          - python-version: "3.12"
            django-version: "3.2"
          - python-version: "3.13"
            django-version: "3.2"

          # Django 4.2 requires Python 3.8-3.12.
          - python-version: "3.13"
            django-version: "4.2"

          # Django 5.1 requires Python 3.10+.
          - python-version: "3.8"
            django-version: "5.1"
          - python-version: "3.9"
            django-version: "5.1"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install "Django~=${{ matrix.django-version }}.0"
      - name: Test with pytest
        run: |
          pytest --no-migrations
